### ISSUE TITLE
Unexpected behavior with large forms - need to scroll between image and form fields

### ISSUE THREAD

**Issue by jmotis** [chnm/Datascribe-module#13] opened 2020-04-08 16:18 UTC
When there is only one image in an item (I assume behavior is different for multiple images but haven't checked yet) filling in the form rapidly results in the image rolling up off the page so you have to scroll up and down to get to the image then back to the later fields in the form.

![lose-image](https://user-images.githubusercontent.com/8195932/78808162-09376480-7993-11ea-94b9-d8903ff8fd1e.png)

**Comment by jimsafley** [comment] 2020-04-08 23:03
I cannot reproduce this. @kimisgold Could this be an style issue, or some weird behavior of the media viewer?

**Comment by jmotis** [comment] 2020-04-09 23:01
I've managed to reproduce the problem but only intermittently. It is probably Safari-specific (I haven't been able to do it on Firefox yet) and may have something to do with tab-navigation in records as it doesn't seem to happen when I use the scrollbar. But it doesn't happen every time. I'll keep playing and see if I can't narrow down what causes the behavior.

**Comment by jmotis** [comment] 2020-04-09 23:14
Okay, so it seems to be consistently caused by the following sequence (in Safari):
1) start a new record
2) rotate the image clockwise 90 degrees (with or without zooming afterwards)
3) select into the first field with the mouse
4) begin tabbing through the fields (with or without filling them)

I tabbed 14 times (to the "is illegible" flag of the fifth field) before the behavior manifested.

It also seems to be caused by (after step 2), scrolling down with the sidebar then clicking into any of the fields after the fifth or sixth one.

**Comment by kimisgold** [comment] 2020-04-22 15:24
May have been incidentally addressed in https://github.com/chnm/Datascribe-module/commit/3f88fc5c9978f320a4309d146d519c8873bff990.

**Closed by kimisgold** 2020-04-22 15:24 UTC
