### ISSUE TITLE
Previous Records and New Record overlay

### ISSUE THREAD

**Issue by dth1692** [chnm/Datascribe-module#46] opened 2020-06-15 22:21 UTC
When I have Previous Records opened and scroll, the Previous Records text overlays the New Record in Edge and Chrome.

![Scrolling in add new record](https://user-images.githubusercontent.com/35391752/84711559-a636f080-af34-11ea-96ad-370e241facdd.JPG)

**Comment by dth1692** [comment] 2020-06-15 23:53
I can add this as a different issue if you think its distinct.  On the Records page in Chrome (not Edge) when I have the window open as a half screen (Netflix on the other half), the line for the box's heading overlays the records list

![half page line overlay](https://user-images.githubusercontent.com/35391752/84716605-9b368d00-af41-11ea-9be4-7fbcaf8b37ef.JPG)

**Comment by kimisgold** [comment] 2020-06-23 20:28
@dth1692 For the record cell overflow, can you provide an example link on the test installation again? Funny how bugs stumbled upon in screen sharing suddenly become elusive when I go to address them.

**Comment by dth1692** [comment] 2020-06-24 01:01
I couldn't get that to repeat now, but I think its because of this whole new overlay issue: 
![Everything scrolls](https://user-images.githubusercontent.com/35391752/85484088-19bfaa00-b594-11ea-9102-f3edc9f08a1d.JPG)

Everything from the Previous Records display scrolls with it when I use the browser scroll
Then when I changed the Window to half size, the cell overflow was different than when I first opened the issue.

![Half screen](https://user-images.githubusercontent.com/35391752/85484317-95b9f200-b594-11ea-8082-08725f8ca56d.JPG)

I got it to happen here-http://datascribetest.chnm.org/admin/datascribe/2/2/7/record/add  and here- https://omeka.jessicaotis.com/admin/datascribe/2/2/5/record/add in Edge and Chrome

**Comment by dth1692** [comment] 2020-06-24 01:04
Actually, that wasn't phrased right- I couldn't get it to repeat the same way, but I think its the number of records in the document I tried changing how the overlay is occurring and how much it intersects the new record

**Comment by mebrett** [comment] 2020-06-25 15:44
I just tried to duplicate this. I was able to do so on Jessica's install. When I went to do it on the datascribetest, I found myself unable to even scroll to the new record fields when I was in an item with a large number of previous records. The specific item I was adding records to is http://datascribetest.chnm.org/admin/datascribe/2/2/6/record

**Comment by dth1692** [comment] 2020-06-25 17:34
I got the inability to scroll in Edge too.  It was fine until opening Previous Records.  Closing the Record Actions sidebar brought back the scroll ability in the New Record but not the page.  After opening a New Record and doing Add+ I was able to get the scroll bars to return.

**Comment by kimisgold** [comment] 2020-06-25 18:51
I think I've at least partially addressed the table overflow in 2ed088300c8b13f5503882a100668e266bba6ac8.

**Comment by dth1692** [comment] 2020-06-27 02:37
I'm still getting the overlay in focus mode where it covers the focus mode and oreintation buttons.  However, I noticed that the overly lay is the border of the image viewer, the tools bar, and the image.  When the item image does not fill the entire display, the Focus mode and layout features are visible in the background.

![Image overlay](https://user-images.githubusercontent.com/35391752/85912795-3ca0c700-b7fd-11ea-8a49-e439d3e2dfba.JPG)
rs

**Comment by kimisgold** [comment] 2020-06-29 12:51
I'm still having trouble reproducing this in Chrome and Edge. @mebrett, can you help pin this down?

**Comment by mebrett** [comment] 2020-06-29 15:46
I'm not able to reproduce this in Chrome, FIrefox, or Safari

**Comment by mebrett** [comment] 2020-06-29 15:50
@kimisgold I'm having trouble reproducing it now.

**Comment by jimsafley** [comment] 2020-07-01 11:34
When the "Previous records" section is opened, the media viewer/record form section seems to have trouble on smaller windows. I decreased the size of my window and the media viewer/record form section does not scroll down. The record form itself does scroll, but only in the tiny, visible part of the page.

![datascribe](https://user-images.githubusercontent.com/141955/86239151-c4276680-bb6c-11ea-8bac-c2d2e1bd6339.png)

**Comment by kimisgold** [comment] 2020-07-01 14:10
If I'm understanding your comment correctly, I think I've addressed this in the main branch, with some explanation in https://github.com/chnm/Datascribe-module/issues/53#issuecomment-651336072. You might want to merge them into the `media-viewer-save-state` branch.

**Comment by kimisgold** [comment] 2020-07-01 19:20
@dth1692's overlay errors were possibly a result of using Microsoft Edge Legacy. They work in the current Microsoft Edge.

We confirmed that @jimsafley's prev/next records issue was resolved in #53.

**Closed by kimisgold** 2020-07-01 19:20 UTC
